### ISSUE TITLE
Problems I ran in and what I did to solve them(, or not)

### ISSUE THREAD

**Issue by 2103simon** [xEnVrE/visual-tactile-simulation-environment#1] opened 2020-04-14 10:03 UTC
Hi @xEnVrE ,

at the first point 'Requirements' I made the following steps:

```cd $ROBOTOLOGY_SUPERBUILD_SOURCE_DIR/robotology/icub-gazebo
git remote add experimental https://github.com/xenvre/icub-gazebo.git
git fetch experimental
```

followed by ```git checkout impl/fingers``` which lead to the following error message: 

```error: Your local changes to the following files would be overwritten by checkout:
icub_with_hands/icub_with_hands.sdf

Please commit your changes or stash them before you switch branches.
```

running `git stash` first solved the problem and lead to the following output:
 
```
Branch 'impl/fingers' set up to track remote branch 'impl/fingers' from 'experimental'.
Switched to a new branch 'impl/fingers'
```

with that, the other points are working as expected.

**Comment by 2103simon** [comment] 2020-04-14 10:51
Hi @xEnVrE ,

I was able to fulfill all the steps until 'How to run'.
Now I opened three shells, in the first one it is running ```yarpserver --write```, in the second one ```yarpdev --device transformServer --ROS::enable_ros_publisher false --ROS::enable_ros_subscriber false''' and in the third and last ```gazebo $ROBOTOLOGY_SUPERBUILD_INSTALL_PREFIX/share/gazebo/worlds/vte_scenario.sdf````. 
Now I thought I would find the environment with the table and one object placed on it in the 'Insert' section under ```/share/gazebo/worlds/``` with the name ```vte_scenario```, but I do not find it. I also tried to find the path manually, but without success.

Any help is appreciated. Thanks in advance!

**Comment by xEnVrE** [comment] 2020-04-14 11:21
Hi @2103simon,

after running `gazebo` with the additional parameter 

```
$ROBOTOLOGY_SUPERBUILD_INSTALL_PREFIX/share/gazebo/worlds/vte_scenario.sdf
```

it should load the model automatically.

Hence, there is something wrong somewhere.

Can you please check that the world exists in the path `$ROBOTOLOGY_SUPERBUILD_INSTALL_PREFIX/share/gazebo/worlds` ?

**Comment by 2103simon** [comment] 2020-04-14 11:24
```root@d621edc3556f:/robotology-superbuild/build/install/share/gazebo/worlds# ls
icub.world  icub_fixed.world```

**Comment by 2103simon** [comment] 2020-04-14 11:27
That can be found here: ```root@d621edc3556f:/visual-tactile-simulation-environment/worlds# ls```

```vte_scenario.sdf```

**Comment by xEnVrE** [comment] 2020-04-14 11:27
Nope, not the `vte_scenario` world.

The issue is due to a typo in the documentation, sorry.

```
cmake -DCMAKE_PREFIX_INSTALL=$ROBOTOLOGY_SUPERBUILD_INSTALL_PREFIX ../
```

This command should have been

```
cmake -DCMAKE_INSTALL_PREFIX=$ROBOTOLOGY_SUPERBUILD_INSTALL_PREFIX ../
```

You should try to remove the entire content of `visual-tactile-simulation-environment/build` and repeat the command with the new command.

**Comment by 2103simon** [comment] 2020-04-14 11:34
YES!
![grafik](https://user-images.githubusercontent.com/60852381/79220623-a2172580-7e54-11ea-9e53-141caf6b3dc2.png)

**Comment by 2103simon** [comment] 2020-04-14 11:39
There is one more point making me worry. Is this ok:

```
yarp: Port /right_hand/skinManager/skin_events:o active at tcp://172.17.0.2:10119/
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
[ERROR]FrameTransformClient::getTransform() frames  /inertial  and  /iCub/frame  are not connected
[ERROR]GazeboYarpSkin:OnWorldUpdate error: unable to get the pose of the root link of the robot.
```

?

**Comment by xEnVrE** [comment] 2020-04-14 11:41
It depends!

Are these messages continuously flowing? If they stopped coming out it is fine. During the first iterations of the simulation, some plugin cannot find the pose of the robot as some components are still in their initialization phase.

**Comment by 2103simon** [comment] 2020-04-14 11:44
Ok, thank you. It's only running in the beginning and then it stops :)

**Comment by xEnVrE** [comment] 2020-04-14 11:48
If everything is working fine, I would close the issue. Let me know :)

**Comment by 2103simon** [comment] 2020-04-14 12:46
I will open another Issue on "Make the dolls dance - How iCub can be moved", this one can be closed. Do you agree?

**Comment by xEnVrE** [comment] 2020-04-14 12:51
Since that issue is related to the simulation of iCub in general and it is not specific to this environment, can I ask you to open it in the `workbook` repository? :)

**Closed** 2020-04-14 12:51 UTC
